export interface FootballSearchPromotion {
  id: number;
  aliases: readonly string[];
  priority: number;
}

export const LEAGUE_SEARCH_PROMOTIONS: readonly FootballSearchPromotion[] = [
  {
    id: 1,
    aliases: ['world cup', 'fifa world cup', 'fifa', 'world', 'wc'],
    priority: 1000,
  },
  {
    id: 15,
    aliases: ['fifa club world cup', 'club world cup'],
    priority: 850,
  },
  {
    id: 2,
    aliases: ['champions league', 'uefa champions league', 'ucl'],
    priority: 950,
  },
  {
    id: 39,
    aliases: ['premier league', 'english premier league', 'epl'],
    priority: 900,
  },
  {
    id: 140,
    aliases: ['la liga', 'laliga', 'spanish league'],
    priority: 880,
  },
];

export interface PlayerSearchPromotion {
  id?: number;
  canonicalName: string;
  lookupQuery: string;
  aliases: readonly string[];
  priority: number;
}

const player = (
  canonicalName: string,
  lookupQuery: string,
  priority: number,
  aliases: readonly string[] = [],
  id?: number,
): PlayerSearchPromotion => ({
  ...(id ? { id } : {}),
  canonicalName,
  lookupQuery,
  aliases: Array.from(
    new Set([
      canonicalName.toLowerCase(),
      lookupQuery.toLowerCase(),
      ...aliases,
    ]),
  ),
  priority,
});

export const PLAYER_SEARCH_PROMOTIONS: readonly PlayerSearchPromotion[] = [
  player(
    'Lionel Messi',
    'messi',
    1000,
    ['leo messi', 'l messi', 'lionel andres messi', 'lionel'],
    154,
  ),
  player(
    'Cristiano Ronaldo',
    'ronaldo',
    999,
    ['cristiano', 'cr7', 'c ronaldo', 'cristiano ronaldo dos santos aveiro'],
    874,
  ),
  player(
    'Neymar Junior',
    'neymar',
    998,
    ['neymar jr', 'neymar junior', 'neymar da silva santos junior'],
    276,
  ),
  player(
    'Kylian Mbappe',
    'mbappe',
    997,
    ['kylian mbappe', 'k mbappe', 'kylian', 'mbappe'],
    278,
  ),
  player(
    'Erling Haaland',
    'haaland',
    996,
    ['erling haaland', 'e haaland', 'erling'],
    1100,
  ),
  player(
    'Mohamed Salah',
    'salah',
    995,
    ['mo salah', 'mohamed salah', 'm salah', 'salah'],
    306,
  ),
  player(
    'Vinicius Junior',
    'vinicius',
    994,
    ['vinicius junior', 'vinicius jr', 'vini junior', 'vini jr', 'vini'],
    762,
  ),
  player(
    'Jude Bellingham',
    'bellingham',
    993,
    ['jude bellingham', 'jude', 'j. bellingham'],
    129718,
  ),
  player('Lamine Yamal', 'lamine yamal', 992, ['yamal', 'lamine'], 386828),
  player(
    'Robert Lewandowski',
    'lewandowski',
    991,
    ['robert lewandowski', 'lewa'],
    147229,
  ),
  player(
    'Harry Kane',
    'kane',
    990,
    ['kane', 'h kane', 'H. Kane', 'Harry Edward'],
    184,
  ),
  player('Kevin De Bruyne', 'de bruyne', 989, ['kevin de bruyne', 'kdb'], 629),
  player('Rodri', 'rodri', 988, ['rodrigo hernandez'], 44),
  player('Bukayo Saka', 'saka', 987, ['bukayo saka', 'bukayo'], 1460),
  player('Phil Foden', 'foden', 986, ['phil foden'], 631),
  player('Cole Palmer', 'cole palmer', 985, ['palmer', 'cold palmer'], 152982),
  player('Florian Wirtz', 'wirtz', 984, ['florian wirtz'], 203224),
  player('Jamal Musiala', 'musiala', 983, ['jamal musiala'], 181812),
  player('Pedri', 'pedri', 982, ['pedro gonzalez'], 133609),
  player('Gavi', 'gavi', 981, ['pablo gavi'], 296667),
  player('Raphinha', 'raphinha', 980, ['raphael dias belloli'], 1496),
  player('Lautaro Martinez', 'lautaro martinez', 979, ['lautaro'], 217),
  player('Julian Alvarez', 'julian alvarez', 978, ['julian'], 6009),
  player('Alexander Isak', 'isak', 977, ['alexander isak'], 2864),
  player('Victor Osimhen', 'osimhen', 976, ['victor osimhen'], 2780),
  player(
    'Khvicha Kvaratskhelia',
    'kvaratskhelia',
    975,
    ['khvicha', 'kvara'],
    483,
  ),
  player('Ousmane Dembele', 'dembele', 974, ['ousmane dembele'], 153),
  player('Antoine Griezmann', 'griezmann', 973, ['antoine griezmann'], 56),
  player('Karim Benzema', 'benzema', 972, ['karim benzema'], 759),
  player('Sadio Mane', 'sadio mane', 971, ['mane'], 304),
  player('Luis Diaz', 'luis diaz', 970, ['lucho diaz'], 2489),
  player(
    'Son Heung Min',
    'son heung min',
    969,
    ['heung min son', 'sonny'],
    186,
  ),
  player('Bruno Fernandes', 'bruno fernandes', 968, ['bruno']),
  player('Bernardo Silva', 'bernardo silva', 967, ['bernardo']),
  player('Martin Odegaard', 'odegaard', 966, ['martin odegaard']),
  player('Declan Rice', 'declan rice', 965, ['rice']),
  player('Joshua Kimmich', 'kimmich', 964, ['joshua kimmich']),
  player('Toni Kroos', 'toni kroos', 963, ['kroos']),
  player('Luka Modric', 'modric', 962, ['luka modric']),
  player('Federico Valverde', 'valverde', 961, [
    'federico valverde',
    'fede valverde',
  ]),
  player('Eduardo Camavinga', 'camavinga', 960, ['eduardo camavinga']),
  player('Aurelien Tchouameni', 'tchouameni', 959, ['aurelien tchouameni']),
  player('Enzo Fernandez', 'enzo fernandez', 958, ['enzo']),
  player('Alexis Mac Allister', 'mac allister', 957, ['alexis mac allister']),
  player('Virgil Van Dijk', 'van dijk', 956, ['virgil van dijk', 'vvd']),
  player('William Saliba', 'saliba', 955, ['william saliba']),
  player('Ruben Dias', 'ruben dias', 954, ['rubendias']),
  player('Marquinhos', 'marquinhos', 953),
  player('Antonio Rudiger', 'rudiger', 952, ['antonio rudiger']),
  player('Achraf Hakimi', 'hakimi', 951, ['achraf hakimi']),
  player('Trent Alexander Arnold', 'trent alexander arnold', 950, [
    'trent',
    'taa',
  ]),
  player('Alphonso Davies', 'alphonso davies', 949, ['davies']),
  player('Theo Hernandez', 'theo hernandez', 948, ['theo']),
  player('Joao Cancelo', 'joao cancelo', 947, ['cancelo']),
  player('Dani Carvajal', 'carvajal', 946, ['dani carvajal']),
  player('Alisson Becker', 'alisson', 945, ['alisson becker']),
  player('Ederson', 'ederson', 944, ['ederson moraes']),
  player('Thibaut Courtois', 'courtois', 943, ['thibaut courtois']),
  player('Gianluigi Donnarumma', 'donnarumma', 942, ['gianluigi donnarumma']),
  player('Emiliano Martinez', 'emiliano martinez', 941, [
    'dibu martinez',
    'dibu',
  ]),
  player('Manuel Neuer', 'neuer', 940, ['manuel neuer']),
  player('Marc Andre Ter Stegen', 'ter stegen', 939, ['marc andre ter stegen']),
  player('Jan Oblak', 'oblak', 938, ['jan oblak']),
  player('Paulo Dybala', 'dybala', 937, ['paulo dybala']),
  player('Romelu Lukaku', 'lukaku', 936, ['romelu lukaku']),
  player('Marcus Rashford', 'rashford', 935, ['marcus rashford']),
  player('Gabriel Martinelli', 'martinelli', 934, ['gabriel martinelli']),
  player('Gabriel Jesus', 'gabriel jesus', 933),
  player('Kai Havertz', 'havertz', 932, ['kai havertz']),
  player('Darwin Nunez', 'darwin nunez', 931, ['darwin']),
  player('Luis Suarez', 'luis suarez', 930, ['suarez']),
  player('Sergio Ramos', 'sergio ramos', 929, ['ramos']),
  player('Sergio Busquets', 'busquets', 928, ['sergio busquets']),
  player('Andres Iniesta', 'iniesta', 927, ['andres iniesta']),
  player('Xavi Hernandez', 'xavi', 926, ['xavi hernandez']),
  player('Ronaldinho', 'ronaldinho', 925, ['ronaldinho gaucho']),
  player('Ronaldo Nazario', 'ronaldo nazario', 924, ['r9', 'fenomeno']),
  player('Zinedine Zidane', 'zidane', 923, ['zinedine zidane', 'zizou']),
  player('Diego Maradona', 'maradona', 922, ['diego maradona']),
  player('Pele', 'pele', 921),
  player('Paolo Maldini', 'maldini', 920, ['paolo maldini']),
  player('Thierry Henry', 'henry', 919, ['thierry henry']),
  player('Didier Drogba', 'drogba', 918, ['didier drogba']),
  player('Samuel Etoo', 'samuel etoo', 917, ['etoo']),
  player('Wayne Rooney', 'rooney', 916, ['wayne rooney']),
  player('David Beckham', 'beckham', 915, ['david beckham']),
  player('Zlatan Ibrahimovic', 'ibrahimovic', 914, ['zlatan']),
  player('Gareth Bale', 'gareth bale', 913, ['bale']),
  player('Thomas Muller', 'thomas muller', 912, ['muller']),
  player('Leroy Sane', 'leroy sane', 911, ['sane']),
  player('Kingsley Coman', 'coman', 910, ['kingsley coman']),
  player('Ademola Lookman', 'lookman', 909, ['ademola lookman']),
  player('Michael Olise', 'olise', 908, ['michael olise']),
  player('Nico Williams', 'nico williams', 907),
  player('Dani Olmo', 'dani olmo', 906, ['olmo']),
  player('Joao Felix', 'joao felix', 905, ['felix']),
  player('Rafael Leao', 'rafael leao', 904, ['leao']),
  player('Dusan Vlahovic', 'vlahovic', 903, ['dusan vlahovic']),
  player('Hakan Calhanoglu', 'calhanoglu', 902, ['hakan calhanoglu']),
  player('Ilkay Gundogan', 'gundogan', 901, ['ilkay gundogan']),
  player('Frenkie De Jong', 'frenkie de jong', 900, ['de jong']),
  player('Joao Neves', 'joao neves', 899),
  player('Vitinha', 'vitinha', 898),
  player('Dominik Szoboszlai', 'szoboszlai', 897, ['dominik szoboszlai']),
  player('Cody Gakpo', 'gakpo', 896, ['cody gakpo']),
  player('Sandro Tonali', 'tonali', 895, ['sandro tonali']),
  player('Christian Pulisic', 'pulisic', 894, ['christian pulisic']),
  player('Mason Mount', 'mason mount', 893),
  player('Jack Grealish', 'grealish', 892, ['jack grealish']),
  player('Memphis Depay', 'memphis depay', 891, ['depay']),
  player('Endrick', 'endrick', 890),
  player('Arda Guler', 'arda guler', 889, ['guler']),
  player('Pau Cubarsi', 'pau cubarsi', 888, ['cubarsi']),
  player('Warren Zaire Emery', 'zaire emery', 887, ['warren zaire emery']),
  player('Desire Doue', 'desire doue', 886, ['doue']),
  player('Savinho', 'savinho', 885),
  player('Estevao', 'estevao', 884),
  player('Jhon Duran', 'jhon duran', 883, ['duran']),
  player('Benjamin Sesko', 'sesko', 882, ['benjamin sesko']),
  player('Viktor Gyokeres', 'gyokeres', 881, ['viktor gyokeres']),

  player('Aitana Bonmati', 'aitana bonmati', 880, ['aitana', 'bonmati']),
  player('Alexia Putellas', 'alexia putellas', 879, ['alexia', 'putellas']),
  player('Sam Kerr', 'sam kerr', 878),
  player('Lauren James', 'lauren james', 877),
  player('Mary Earps', 'mary earps', 876),
  player('Lucy Bronze', 'lucy bronze', 875),
  player('Leah Williamson', 'leah williamson', 874),
  player('Alessia Russo', 'alessia russo', 873, ['russo']),
  player('Beth Mead', 'beth mead', 872),
  player('Chloe Kelly', 'chloe kelly', 871),
  player('Sophia Smith', 'sophia smith', 870),
  player('Trinity Rodman', 'trinity rodman', 869, ['rodman']),
  player('Mallory Swanson', 'mallory swanson', 868),
  player('Lindsey Horan', 'lindsey horan', 867),
  player('Alex Morgan', 'alex morgan', 866),
  player('Megan Rapinoe', 'megan rapinoe', 865, ['rapinoe']),
  player('Marta', 'marta', 864),
  player('Ada Hegerberg', 'ada hegerberg', 863, ['hegerberg']),
  player('Caroline Graham Hansen', 'caroline graham hansen', 862, [
    'graham hansen',
  ]),
  player('Salma Paralluelo', 'salma paralluelo', 861, ['salma']),
  player('Barbra Banda', 'barbra banda', 860, ['banda']),
  player('Khadija Shaw', 'khadija shaw', 859, ['bunny shaw']),
  player('Vivianne Miedema', 'vivianne miedema', 858, ['miedema']),
  player('Pernille Harder', 'pernille harder', 857),
  player('Wendie Renard', 'wendie renard', 856, ['renard']),
] as const satisfies readonly PlayerSearchPromotion[];
